### ISSUE TITLE
Log Agent format 

### ISSUE THREAD

**Issue by AlexLionne** [AlexLionne/confluence#3]
The following format could not be interpreted by the current Parser

```text Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IFSNetworkAgent.IRemotePlayerHost.GetV4(String key, String device, String deviceName, Nullable`1 userId, Nullable`1 licenseId, String application, String version, Boolean is64bOs, Boolean is64bApp, Boolean isPLayerRunning, String xpId, String xpName)
   at IFSNetworkAgent.IFSRemotePlayerClient.GetV4(String key, String deviceKey, String deviceName, Nullable`1 userId, Nullable`1 licenseId, String application, String version, Boolean is64bOs, Boolean is64bApp, Boolean isPLayerRunning, String xpId, String xpName)
   at IntuifacePlayerAgent.Controllers.Polling.XCyGCcWltk(Object  )
26/04/2019 15:59:14 NOTICE;Polling POLLING_FAST 4000 
26/04/2019 15:59:18 NOTICE;Polling STATUS  
26/04/2019 15:59:22 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 15:59:30 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 16:00:03 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 16:00:36 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 16:01:08 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 16:01:41 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 
26/04/2019 16:02:14 NOTICE;Polling SNAPSHOT quality=70&height=200&width=200 ```

**Comment by AlexLionne** [comment]
Looking to **Collection<Pattern>`**

**Comment by AlexLionne** [comment]
related branch https://github.com/AlexLionne/confluence/tree/dev%40intuiface-PatternCollection
